# Generated by Django 2.0.2 on 2018-08-08 10:04

from django.db import migrations, models
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('on_field_attendance_app', '0002_place_abc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.AlterField(
            model_name='task',
            name='address',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
