# Generated by Django 2.1 on 2018-08-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_field_attendance_app', '0005_auto_20180808_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
