# Generated by Django 2.1 on 2018-08-09 22:47

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('on_field_attendance_app', '0006_auto_20180810_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='address',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
