# Generated by Django 2.1 on 2018-08-10 09:01

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('on_field_attendance_app', '0008_auto_20180810_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='location',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
