# Generated by Django 2.0.2 on 2018-08-10 09:23

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('on_field_attendance_app', '0009_auto_20180810_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='address',
            field=location_field.models.plain.PlainLocationField(blank=True, max_length=63, null=True),
        ),
    ]
