# Generated by Django 2.0.2 on 2018-08-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('on_field_attendance_app', '0011_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='parent_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='on_field_attendance_app.Place'),
        ),
    ]
